fix: `BaseEpisodeLog.pk` field conflict with `JsonModel.pk`
Error log:

pydantic_core._pydantic_core.ValidationError: 1 validation error for EpisodeLog
pk
  Input should be a valid string [type=string_type, input_value=<redis_om.model.model.Exp...bject at 0x7ff30bb94d10>, input_type=ExpressionProxy]
    For further information visit https://errors.pydantic.dev/2.9/v/string_type